version: 3
vars:
  OUTPUT: _site
tasks:
  css:
    internal: true
    cmds:
      - npx tailwindcss --input=style.css --output={{.OUTPUT}}/style.css {{if .WATCH}}--watch{{end}}
  html:
    internal: true
    env:
      ELEVENTY_ENV: "{{.ENV}}"
    cmds:
      - npx eleventy --output={{.OUTPUT}} {{if .SERVE}}--serve{{end}}
  format:
    aliases:
      - fmt
    cmds:
      - npx prettier . --write
  build:
    deps:
      - task: css
      - task: html
        vars:
          ENV: production
  serve:
    deps:
      - task: css
        vars:
          WATCH: true
      - task: html
        vars:
          SERVE: true
